import React from "react";
import Link from "next/link";

export const metadata = {
    title: "Terms of Service | Zebra AI",
    description: "Zebra AI Terms of Service — the rules and guidelines for using our platform.",
};

export default function TermsOfServicePage() {
    return (
        <div className="min-h-screen bg-[#FAFAFA]">
            <nav className="h-16 border-b border-black/5 bg-white/80 backdrop-blur-md sticky top-0 z-50 flex items-center px-8">
                <Link href="/" className="font-black text-lg tracking-tight">Zebra AI</Link>
                <span className="mx-3 text-black/20">·</span>
                <span className="text-sm font-semibold text-black/50">Terms of Service</span>
            </nav>
            <main className="max-w-3xl mx-auto px-6 py-16">
                <h1 className="text-4xl font-black tracking-tight mb-2">Terms of Service</h1>
                <p className="text-sm text-black/40 font-semibold mb-12">Last updated: April 6, 2026</p>

                <div className="prose-zebra space-y-10">
                    <Section title="1. Acceptance of Terms">
                        <p>By accessing or using Zebra AI (&quot;the Service&quot;), available at zebra-ai.app, you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>
                    </Section>

                    <Section title="2. Description of Service">
                        <p>Zebra AI is an AI-powered career document platform that provides:</p>
                        <ul>
                            <li>A real-time resume compiler with live preview.</li>
                            <li>AI-assisted content generation (copilot and RAG assistant).</li>
                            <li>Template-based resume formatting and export.</li>
                            <li>Career analytics and job tracking tools.</li>
                        </ul>
                    </Section>

                    <Section title="3. User Accounts">
                        <ul>
                            <li>You must provide accurate information when creating an account.</li>
                            <li>You are responsible for maintaining the security of your account credentials.</li>
                            <li>You must be at least 16 years old to use the Service.</li>
                            <li>One person per account. Shared accounts are not permitted.</li>
                        </ul>
                    </Section>

                    <Section title="4. Subscription & Payments">
                        <ul>
                            <li><strong>Free Tier:</strong> Access to basic templates, limited AI credits, and standard export.</li>
                            <li><strong>Pro Tier:</strong> Access to premium (Executive) templates, unlimited AI credits, and priority features.</li>
                            <li>Payments are processed securely via Razorpay.</li>
                            <li>Subscriptions auto-renew unless cancelled before the billing date.</li>
                            <li>Refunds are available within 7 days of purchase if no premium features were used.</li>
                        </ul>
                    </Section>

                    <Section title="5. Content Ownership">
                        <ul>
                            <li><strong>Your Content:</strong> You retain full ownership of all resume content you create or upload. Zebra AI does not claim any rights to your content.</li>
                            <li><strong>Our Templates:</strong> Resume templates, designs, and UI elements are proprietary to Zebra AI and may not be reproduced or distributed.</li>
                            <li><strong>AI-Generated Content:</strong> Suggestions generated by AI are provided as-is. You are responsible for reviewing and using them appropriately.</li>
                        </ul>
                    </Section>

                    <Section title="6. Acceptable Use">
                        <p>You agree NOT to:</p>
                        <ul>
                            <li>Use the Service for any illegal or unauthorized purpose.</li>
                            <li>Attempt to bypass premium features, paywalls, or export restrictions.</li>
                            <li>Reverse-engineer, decompile, or extract source code from the Service.</li>
                            <li>Use automated tools to scrape content or abuse APIs.</li>
                            <li>Upload malicious content, viruses, or harmful code.</li>
                            <li>Share, resell, or redistribute premium templates.</li>
                        </ul>
                    </Section>

                    <Section title="7. AI Disclaimer">
                        <p>AI features powered by Google Gemini and Gemma models are provided as an assistive tool:</p>
                        <ul>
                            <li>AI suggestions may contain inaccuracies — always review before using.</li>
                            <li>Zebra AI is not responsible for hiring outcomes based on AI-generated content.</li>
                            <li>AI processing is subject to third-party provider availability and terms.</li>
                        </ul>
                    </Section>

                    <Section title="8. Limitation of Liability">
                        <p>Zebra AI is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted by law:</p>
                        <ul>
                            <li>We are not liable for any indirect, incidental, or consequential damages.</li>
                            <li>Our total liability shall not exceed the amount you paid in the 12 months preceding the claim.</li>
                            <li>We do not guarantee job placement, interview success, or career outcomes.</li>
                        </ul>
                    </Section>

                    <Section title="9. Termination">
                        <p>We may suspend or terminate your account if you violate these Terms. You may delete your account at any time from Settings. Upon termination, your data will be permanently deleted within 30 days.</p>
                    </Section>

                    <Section title="10. Changes to Terms">
                        <p>We reserve the right to modify these Terms at any time. Significant changes will be communicated via email or in-app notification. Continued use after changes constitutes acceptance.</p>
                    </Section>

                    <Section title="11. Governing Law">
                        <p>These Terms are governed by the laws of India. Any disputes will be resolved in the courts of Kolkata, West Bengal.</p>
                    </Section>

                    <Section title="12. Contact">
                        <p>For questions about these Terms, contact us at: <strong>legal@zebra-ai.app</strong></p>
                    </Section>
                </div>

                <div className="mt-16 pt-8 border-t border-black/5 flex items-center justify-between text-sm text-black/40">
                    <Link href="/privacy" className="hover:text-black transition-colors font-semibold">← Privacy Policy</Link>
                    <Link href="/" className="hover:text-black transition-colors font-semibold">← Back to Home</Link>
                </div>
            </main>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section>
            <h2 className="text-xl font-black tracking-tight mb-4">{title}</h2>
            <div className="text-[15px] text-black/70 leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_li]:text-black/70">
                {children}
            </div>
        </section>
    );
}
